<?php /** @var $escaper Escaper */

use Magento\Framework\Escaper;

?>
<?php $_source = $block->getSource() ?>
<?php $_order = $block->getOrder() ?>
<?php $block->setPriceDataObject($_source) ?>

<?php if ((float)$_source->getDiscountAmount()) : ?>
    <tr>
        <td class="label">
            <?php if ($_order->getCouponCode()) : ?>
                <?= $escaper->escapeHtml(__('Discount (%1)', $_order->getCouponCode())) ?>
            <?php else : ?>
                <?= $escaper->escapeHtml(__('Discount')) ?>
            <?php endif; ?>
        </td>
        <td><?= /* @noEscape */
            $block->displayPriceAttribute('discount_amount') ?></td>
    </tr>
<?php endif; ?>
