<?php
/** @var $escaper Escaper */

use Magento\Framework\Escaper; ?>

<?php $_source = $block->getSource() ?>
<?php $block->setPriceDataObject($_source) ?>

<?php if ((float)$_source->getDataUsingMethod($block->getSourceField())) : ?>
    <tr>
        <td class="label">
            <?php if ($block->getStrong()) : ?>
            <strong>
                <?php endif; ?>
                <?= $escaper->escapeHtml(__($block->getLabel())) ?>
                <?php if ($block->getStrong()) : ?>
            </strong>
        <?php endif; ?>
        </td>
        <td <?= $block->getHtmlClass() ? ('class="' . $escaper->escapeHtmlAttr($block->getHtmlClass()) . '"') : '' ?>>
            <?php if ($block->getStrong()) : ?><strong><?php endif; ?>
                <?= /* @noEscape */
                $block->displayPriceAttribute($block->getSourceField()) ?>
                <?php if ($block->getStrong()) : ?></strong><?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
