<?php
use Magento\Framework\Escaper;
use Magento\Framework\Math\Random;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Sales\Block\Adminhtml\Order\Totals\Tax;
use Magento\Tax\Helper\Data;

/**
 * @var $escaper Escaper
 * @var $block Tax
 * @var SecureHtmlRenderer $secureRenderer
 */
$_source    = $block->getSource();
$_order     = $block->getOrder();
$_fullInfo  = $block->getFullTaxInfo();
/** @var Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
/** @var Random $randomHelper */
$randomHelper = $block->getData('randomHelper');
?>

<?php if ($block->displayFullSummary() && $_fullInfo): ?>
<tr class="summary-total">
<?php else: ?>
<tr>
<?php endif; ?>
    <td class="label">
        <div class="summary-collapse" tabindex="0">
            <?php if ($taxHelper->displayFullSummary()): ?>
                <?= $escaper->escapeHtml(__('Total Tax')) ?>
            <?php else: ?>
                <?= $escaper->escapeHtml(__('Tax')) ?>
            <?php endif;?>
        </div>
    </td>
    <td>
        <?= /* @noEscape */ $block->displayAmount($_source->getTaxAmount(), $_source->getBaseTaxAmount()) ?>
    </td>
</tr>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    "expandDetails(this, '.summary-details')",
    'tr.summary-total'
) ?>
<?php if ($block->displayFullSummary()): ?>
    <?php $isTop = 1; ?>
    <?php if (isset($_fullInfo[0]['rates'])): ?>
        <?php foreach ($_fullInfo as $info): ?>
            <?php if (isset($info['hidden']) && $info['hidden']):
                continue;
            endif; ?>
            <?php
            $percent    = $info['percent'];
            $amount     = $info['amount'];
            $baseAmount = $info['base_amount'];
            $rates      = $info['rates'];
            $isFirst    = 1;
            ?>

            <?php foreach ($rates as $rate): ?>
                <tr id="rate-<?= /* @noEscape */ $rate->getId() ?>"
                    class="summary-details<?= ($isTop ? ' summary-details-first' : '') ?>">
                    <?php if ($rate['percent'] !== null): ?>
                        <td class="admin__total-mark">
                            <?= $escaper->escapeHtml($rate['title']) ?> (<?= (float)$rate['percent'] ?>%)<br />
                        </td>
                    <?php else: ?>
                        <td class="admin__total-mark"><?= $escaper->escapeHtml($rate['title']) ?><br /></td>
                    <?php endif; ?>
                    <?php if ($isFirst): ?>
                        <td rowspan="<?= count($rates) ?>">
                            <?= /* @noEscape */ $block->displayAmount($amount, $baseAmount) ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display:none;", 'tr#rate-' . $rate->getId()) ?>
                <?php
                $isFirst = 0;
                $isTop = 0;
                ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <?php foreach ($_fullInfo as $info): ?>
            <?php
            $percent    = $info['percent'];
            $amount     = $info['tax_amount'];
            $baseAmount = $info['base_tax_amount'];
            $isFirst    = 1;
            $infoId = $randomHelper->getRandomString(20);
            ?>
            <tr id="info-<?= /* @noEscape */ $infoId ?>"
                class="summary-details<?= ($isTop ? ' summary-details-first' : '') ?>">
                <?php if ($info['percent'] !== null): ?>
                    <td class="admin__total-mark">
                        <?= $escaper->escapeHtml($info['title']) ?> (<?= (float)$info['percent'] ?>%)<br />
                    </td>
                <?php else: ?>
                    <td class="admin__total-mark"><?= $escaper->escapeHtml($info['title']) ?><br /></td>
                <?php endif; ?>
                    <td><?= /* @noEscape */ $block->displayAmount($amount, $baseAmount) ?></td>
            </tr>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display:none;", 'tr#info-' . $infoId) ?>
            <?php
            $isFirst = 0;
            $isTop = 0;
            ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif;?>

