<?php
/** @var $escaper \Magento\Framework\Escaper */
?>
<div class="messages">
    <div class="message message-notice">
        <div class="message-inner">
            <div class="message-content">
                <?= $escaper->escapeHtml(
                    __('Changing address information will not recalculate shipping, tax or other order amount.')
                ) ?>
            </div>
        </div>
    </div>
</div>

<div class="fieldset admin__fieldset-wrapper">
    <legend class="legend admin__legend">
        <span><?= $escaper->escapeHtml($block->getHeaderText()) ?></span>
    </legend>
    <br>
    <div class="form-inline" data-mage-init='{"Magento_Sales/order/edit/address/form":{}}'>
        <?= $block->getForm()->toHtml() ?>
    </div>
</div>
